"""Eliminar campo stock de productos

Revision ID: 117c38e2ded8
Revises: 80d76421eb03
Create Date: 2025-09-07 09:27:06.177736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117c38e2ded8'
down_revision = '80d76421eb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
