"""Agrega email, contacto y telefono_contacto a clientes

Revision ID: 11fd368ffee0
Revises: 
Create Date: 2025-08-30 11:56:08.761811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fd368ffee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('contacto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefono_contacto', sa.String(length=20), nullable=True))
        batch_op.alter_column('rfc',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('rfc',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('telefono_contacto')
        batch_op.drop_column('contacto')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
