"""Add subtotal to Venta

Revision ID: 26807e5dee37
Revises: c79136cb609b
Create Date: 2025-09-05 15:25:44.599361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26807e5dee37'
down_revision = 'c79136cb609b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('subtotal')

    # ### end Alembic commands ###
