"""Aumentar largo del campo grupo en medicamentos

Revision ID: 2990adb6899e
Revises: f3dc6dff893d
Create Date: 2025-09-01 17:21:36.961260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2990adb6899e'
down_revision = 'f3dc6dff893d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.alter_column('grupo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.alter_column('grupo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
