"""Agrega columna punto_reorden

Revision ID: 6fb05a215f58
Revises: 6b30e8be2050
Create Date: 2025-09-01 13:14:23.777812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb05a215f58'
down_revision = '6b30e8be2050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
