"""Add descuento to Venta

Revision ID: 80d76421eb03
Revises: df49e686696d
Create Date: 2025-09-05 15:32:40.306181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d76421eb03'
down_revision = 'df49e686696d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('descuento')

    # ### end Alembic commands ###
