"""Ajusta tipo de contraseña a 255 y agrega columnas faltantes

Revision ID: bcf779682d5e
Revises: 6fb05a215f58
Create Date: 2025-09-01 15:34:51.570079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bcf779682d5e'
down_revision = '6fb05a215f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('punto_reorden', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('nombre_comercial',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('nombre_generico',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('laboratorio',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('presentacion',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('grupo',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('no_hay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('fecha_registro')

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacto', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telefono_contacto', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('salidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('producto_tipo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('eliminada', sa.Boolean(), nullable=True))
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('iva_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('valor_iva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.drop_column('tipo_producto')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_modificacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('fecha_modificacion')

    with op.batch_alter_table('salidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_producto', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('valor_iva',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('iva_porcentaje',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('eliminada')
        batch_op.drop_column('usuario_id')
        batch_op.drop_column('cliente_id')
        batch_op.drop_column('producto_tipo')
        batch_op.drop_column('fecha')

    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('fecha_modificacion')
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('telefono_contacto')
        batch_op.drop_column('contacto')

    with op.batch_alter_table('no_hay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('fecha_modificacion')
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.alter_column('grupo',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('presentacion',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('laboratorio',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nombre_generico',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nombre_comercial',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('punto_reorden')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('fecha_modificacion')
        batch_op.drop_column('fecha_creacion')

    # ### end Alembic commands ###
