"""Add metodo_pago to Venta

Revision ID: c79136cb609b
Revises: 8f9713fdc056
Create Date: 2025-09-05 15:20:47.126393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79136cb609b'
down_revision = '8f9713fdc056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metodo_pago', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_column('metodo_pago')

    # ### end Alembic commands ###
