"""Agrega folio_factura a Compra

Revision ID: f1bd564d60e3
Revises: 2990adb6899e
Create Date: 2025-09-01 20:49:38.635711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bd564d60e3'
down_revision = '2990adb6899e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folio_factura', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('folio_factura')

    # ### end Alembic commands ###
