"""Agrega campo descuento a medicamentos y dispositivos médicos

Revision ID: f2904c74fd2e
Revises: 3ac93c20356e
Create Date: 2025-08-31 12:54:06.878058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2904c74fd2e'
down_revision = '3ac93c20356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivos_medicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento', sa.Float(), nullable=True))

    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicamentos', schema=None) as batch_op:
        batch_op.drop_column('descuento')

    with op.batch_alter_table('dispositivos_medicos', schema=None) as batch_op:
        batch_op.drop_column('descuento')

    # ### end Alembic commands ###
