"""Agrega campo activo a DispositivoMedico

Revision ID: f3dc6dff893d
Revises: bcf779682d5e
Create Date: 2025-09-01 15:41:57.686944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3dc6dff893d'
down_revision = 'bcf779682d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivos_medicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dispositivos_medicos', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
